version: 2

builds:
  - skip: true

dockers_v2:
  - images:
      - "docker.io/nextinsurancedevops/tagemon"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - "linux/amd64"
    labels:
      org.opencontainers.image.version: "{{ .Version }}"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - api/
      - internal/

release:
  footer: |
    ## Docker Images 🐳
    
    This release is available as a Docker image:
    
    ```bash
    docker pull docker.io/nextinsurancedevops/tagemon:{{ .Tag }}
    ```
    
    Or use the latest tag:
    
    ```bash
    docker pull docker.io/nextinsurancedevops/tagemon:latest
    ```
    
    ## Helm Chart ⎈
    
    The Helm chart version `{{ .Env.CHART_VERSION }}` is available in the OCI registry.
    
    Install using Helm:
    
    ```bash
    helm install tagemon oci://docker.io/nextinsurancedevops/tagemon --version {{ .Env.CHART_VERSION }}
    ```
    
    Or upgrade an existing installation:
    
    ```bash
    helm upgrade tagemon oci://docker.io/nextinsurancedevops/tagemon --version {{ .Env.CHART_VERSION }}
    ```
    ---
    
    **Full Changelog**: {{ .ReleaseURL }}/compare/{{ .PreviousTag }}...{{ .Tag }}

# Changelog configuration
changelog:
  use: git
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^chore:"
      - "^BREAKING CHANGE:"