version: 2

builds:
  - skip: true

dockers_v2:
  - images:
      - "docker.io/amitshlo/test-tag"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - "linux/amd64"
    labels:
      org.opencontainers.image.version: "{{ .Version }}"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - api/
      - internal/

release:
  footer: |
    ## Docker Images 🐳
    
    This release is available as a Docker image:
    
    ```bash
    docker pull docker.io/amitshlo/test-tag:{{ .Tag }}
    ```
    
    Or use the latest tag:
    
    ```bash
    docker pull docker.io/amitshlo/test-tag:latest
    ```

    ---
    
    **Full Changelog**: {{ .ReleaseURL }}/compare/{{ .PreviousTag }}...{{ .Tag }}

# Changelog configuration
changelog:
  use: git
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^chore:"
      - "^BREAKING CHANGE:"