builds:
  - id: tagemon
    binary: tagemon
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# Changelog configuration
changelog:
  use: git
  sort: asc
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^chore:"
      - "^BREAKING CHANGE:"