//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSRole) DeepCopyInto(out *AWSRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSRole.
func (in *AWSRole) DeepCopy() *AWSRole {
	if in == nil {
		return nil
	}
	out := new(AWSRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportedTag) DeepCopyInto(out *ExportedTag) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportedTag.
func (in *ExportedTag) DeepCopy() *ExportedTag {
	if in == nil {
		return nil
	}
	out := new(ExportedTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResources) DeepCopyInto(out *PodResources) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResources.
func (in *PodResources) DeepCopy() *PodResources {
	if in == nil {
		return nil
	}
	out := new(PodResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tagemon) DeepCopyInto(out *Tagemon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tagemon.
func (in *Tagemon) DeepCopy() *Tagemon {
	if in == nil {
		return nil
	}
	out := new(Tagemon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tagemon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagemonList) DeepCopyInto(out *TagemonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tagemon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagemonList.
func (in *TagemonList) DeepCopy() *TagemonList {
	if in == nil {
		return nil
	}
	out := new(TagemonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TagemonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagemonMetric) DeepCopyInto(out *TagemonMetric) {
	*out = *in
	if in.Statistics != nil {
		in, out := &in.Statistics, &out.Statistics
		*out = make([]Statistics, len(*in))
		copy(*out, *in)
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int32)
		**out = **in
	}
	if in.NilToZero != nil {
		in, out := &in.NilToZero, &out.NilToZero
		*out = new(bool)
		**out = **in
	}
	if in.AddCloudwatchTimestamp != nil {
		in, out := &in.AddCloudwatchTimestamp, &out.AddCloudwatchTimestamp
		*out = new(bool)
		**out = **in
	}
	if in.ThresholdTags != nil {
		in, out := &in.ThresholdTags, &out.ThresholdTags
		*out = make([]ThresholdTag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagemonMetric.
func (in *TagemonMetric) DeepCopy() *TagemonMetric {
	if in == nil {
		return nil
	}
	out := new(TagemonMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagemonSpec) DeepCopyInto(out *TagemonSpec) {
	*out = *in
	if in.ResourceExplorerType != nil {
		in, out := &in.ResourceExplorerType, &out.ResourceExplorerType
		*out = new(string)
		**out = **in
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]AWSRegion, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]AWSRole, len(*in))
		copy(*out, *in)
	}
	if in.Statistics != nil {
		in, out := &in.Statistics, &out.Statistics
		*out = make([]Statistics, len(*in))
		copy(*out, *in)
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int32)
		**out = **in
	}
	if in.ScrapingInterval != nil {
		in, out := &in.ScrapingInterval, &out.ScrapingInterval
		*out = new(int32)
		**out = **in
	}
	if in.NilToZero != nil {
		in, out := &in.NilToZero, &out.NilToZero
		*out = new(bool)
		**out = **in
	}
	if in.AddCloudwatchTimestamp != nil {
		in, out := &in.AddCloudwatchTimestamp, &out.AddCloudwatchTimestamp
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]TagemonMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchTags != nil {
		in, out := &in.SearchTags, &out.SearchTags
		*out = make([]TagemonTag, len(*in))
		copy(*out, *in)
	}
	if in.ExportedTagsOnMetrics != nil {
		in, out := &in.ExportedTagsOnMetrics, &out.ExportedTagsOnMetrics
		*out = make([]ExportedTag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DimensionNameRequirements != nil {
		in, out := &in.DimensionNameRequirements, &out.DimensionNameRequirements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodResources != nil {
		in, out := &in.PodResources, &out.PodResources
		*out = new(PodResources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagemonSpec.
func (in *TagemonSpec) DeepCopy() *TagemonSpec {
	if in == nil {
		return nil
	}
	out := new(TagemonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagemonStatus) DeepCopyInto(out *TagemonStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagemonStatus.
func (in *TagemonStatus) DeepCopy() *TagemonStatus {
	if in == nil {
		return nil
	}
	out := new(TagemonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagemonTag) DeepCopyInto(out *TagemonTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagemonTag.
func (in *TagemonTag) DeepCopy() *TagemonTag {
	if in == nil {
		return nil
	}
	out := new(TagemonTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdTag) DeepCopyInto(out *ThresholdTag) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdTag.
func (in *ThresholdTag) DeepCopy() *ThresholdTag {
	if in == nil {
		return nil
	}
	out := new(ThresholdTag)
	in.DeepCopyInto(out)
	return out
}
